### ISSUE TITLE
How to build latest master?

### ISSUE THREAD

**Issue by Mingun** [pegjs/pegjs#454]
When I try build latest `master` branch, I got error:
```sh
D:\Projects\parsers\pegjs>make
Error: Couldn't find preset "es2015" relative to directory "D:\\Projects\\parsers\\pegjs" while parsing file: D:\Projects\parsers\pegjs\lib\peg.js
    at D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:281:17
    at Array.map (native)
    at OptionManager.resolvePresets (D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:20)
    at OptionManager.mergePresets (D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:254:10)
    at OptionManager.mergeOptions (D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:239:14)
    at OptionManager.init (D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:338:12)
    at File.initOptions (D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (D:\Projects\parsers\pegjs\node_modules\babelify\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at Babelify._flush (D:\Projects\parsers\pegjs\node_modules\babelify\index.js:27:24)
Makefile:66: ошибка выполнения рецепта для цели «browser»
make: *** [browser] Ошибка 1
```
Adding 
```json
{
  "name": "pegjs",
...
  "babel": {
    "presets": [
      "es2015"
    ]
  }
}
```
to `package.json` not resolve this issue

**Comment by Mingun** [comment]
Ok, it appeared, `babel-preset-es2015` package just wasn't installed. I think, it is necessary to add to Readme information on how to build the project since it is absolutely unobvious (for those who are engaged in development under node.js from time to time) that for automatic downloading of dependences it is enough to launch `npm install` in the project folder.

**Comment by dmajda** [comment]
> I think, it is necessary to add to Readme information on how to build the project since it is absolutely unobvious (for those who are engaged in development under node.js from time to time) that for automatic downloading of dependences it is enough to launch `npm install` in the project folder.

I agree this should be documented. I filed #457 to track that.
